export enum OldSquad {
    AS = 1,
    DKK,
    inTeam,
    RAF,
    FB,
    WD,
    TAG,
    ISKRA,
    V,
    BAKR,
    Apex,
    RON,
    ODN,
    RL,
    Wagner,
    BCS,
    OT,
    BAT,
    AXE,
    ORK,
    st31,
    GROM,
    KSK,
    IT,
    SGYR,
    RT,
    VOG,
    MSF,
    CBR,
    CU,
    FNX,
    AV,
    W8,
}

export const squads : OldSquadInfo[] = [
    {id: OldSquad.AS, slots: 7},
    {id: OldSquad.DKK, slots: 10},
    {id: OldSquad.inTeam, slots: 13},
    {id: OldSquad.RAF, slots: 8},
    {id: OldSquad.FB, slots: 12},
    {id: OldSquad.WD, slots: 8},
    {id: OldSquad.TAG, slots: 12},
    {id: OldSquad.ISKRA, slots: 12},
    {id: OldSquad.V, slots: 8},
    {id: OldSquad.BAKR, slots: 6},
    {id: OldSquad.Apex, slots: 12},
    {id: OldSquad.RON, slots: 8},
    {id: OldSquad.ODN, slots: 12},
    {id: OldSquad.RL, slots: 16},
    {id: OldSquad.Wagner, slots: 8},
    {id: OldSquad.BCS, slots: 10},
    {id: OldSquad.OT, slots: 10},
    {id: OldSquad.BAT, slots: 11},
    {id: OldSquad.AXE, slots: 10},
    {id: OldSquad.ORK, slots: 8},
    {id: OldSquad.st31, slots: 12},
    {id: OldSquad.GROM, slots: 9},
    {id: OldSquad.KSK, slots: 10},
    {id: OldSquad.IT, slots: 12},
    {id: OldSquad.SGYR, slots: 8},
    {id: OldSquad.RT, slots: 10},
    {id: OldSquad.VOG, slots: 10},
    {id: OldSquad.MSF, slots: 8},
    {id: OldSquad.CBR, slots: 9},
    {id: OldSquad.CU, slots: 8},
    {id: OldSquad.FNX, slots: 10},
    {id: OldSquad.AV, slots: 10},
    {id: OldSquad.W8, slots: 13},
];

export const preferences : Preferences = {
    [OldSquad.AS]: {with: new Set([OldSquad.st31]), without: new Set([OldSquad.GROM, OldSquad.OT])},
    [OldSquad.DKK]: {with: new Set([OldSquad.AS, OldSquad.FNX, OldSquad.IT, OldSquad.VOG]), without: new Set([OldSquad.OT, OldSquad.RAF, OldSquad.RL, OldSquad.W8, OldSquad.Wagner])},
    [OldSquad.inTeam]: {with: new Set([OldSquad.st31, OldSquad.AS, OldSquad.GROM, OldSquad.RAF, OldSquad.WD]), without: new Set([OldSquad.BAT, OldSquad.CU, OldSquad.IT, OldSquad.W8, OldSquad.Wagner])},
    [OldSquad.RAF]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.inTeam, OldSquad.OT]), without: new Set([OldSquad.Apex, OldSquad.TAG, OldSquad.WD])},
    [OldSquad.FB]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.GROM]), without: new Set([OldSquad.CU, OldSquad.TAG])},
    [OldSquad.WD]: {with: new Set([OldSquad.AS, OldSquad.FB, OldSquad.inTeam, OldSquad.RON, OldSquad.TAG]), without: new Set([OldSquad.AXE, OldSquad.BAT, OldSquad.IT, OldSquad.ODN, OldSquad.OT, OldSquad.RL])},
    [OldSquad.TAG]: {with: new Set([OldSquad.AS, OldSquad.AV, OldSquad.GROM, OldSquad.OT, OldSquad.RON]), without: new Set([OldSquad.inTeam, OldSquad.IT, OldSquad.RAF, OldSquad.RL, OldSquad.SGYR])},
    [OldSquad.ISKRA]: {with: new Set([OldSquad.st31, OldSquad.AS, OldSquad.AV, OldSquad.RON, OldSquad.TAG]), without: new Set([OldSquad.Apex, OldSquad.AXE, OldSquad.CU, OldSquad.ODN, OldSquad.VOG])},
    [OldSquad.V]: {with: new Set([OldSquad.st31, OldSquad.AS, OldSquad.AV, OldSquad.TAG]), without: new Set([OldSquad.KSK, OldSquad.OT])},
    [OldSquad.BAKR]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.KSK, OldSquad.RON, OldSquad.WD]), without: new Set([OldSquad.AXE, OldSquad.CU])},
    [OldSquad.Apex]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.FB, OldSquad.MSF, OldSquad.RON]), without: new Set([OldSquad.BAT, OldSquad.CU, OldSquad.ODN, OldSquad.OT, OldSquad.V])},
    [OldSquad.RON]: {with: new Set([OldSquad.st31, OldSquad.AS, OldSquad.ORK, OldSquad.RT, OldSquad.VOG]), without: new Set([OldSquad.inTeam, OldSquad.ODN, OldSquad.RL, OldSquad.SGYR, OldSquad.Wagner])},
    [OldSquad.ODN]: {with: new Set([OldSquad.BAT, OldSquad.GROM, OldSquad.KSK, OldSquad.RL, OldSquad.SGYR]), without: new Set([OldSquad.Apex, OldSquad.AXE, OldSquad.BAKR, OldSquad.TAG, OldSquad.Wagner])},
    [OldSquad.RL]: {with: new Set([OldSquad.AS, OldSquad.BAT, OldSquad.FNX, OldSquad.ORK, OldSquad.RON, OldSquad.WD]), without: new Set([OldSquad.CU, OldSquad.RAF])},
    [OldSquad.Wagner]: {with: new Set([OldSquad.st31, OldSquad.GROM, OldSquad.KSK, OldSquad.RON, OldSquad.W8]), without: new Set([OldSquad.BAKR, OldSquad.CU, OldSquad.inTeam, OldSquad.TAG])},
    [OldSquad.BCS]: {with: new Set([OldSquad.st31, OldSquad.CBR, OldSquad.KSK, OldSquad.RAF, OldSquad.WD]), without: new Set([OldSquad.AV, OldSquad.AXE, OldSquad.BAT, OldSquad.CU])},
    [OldSquad.OT]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.W8]), without: new Set([OldSquad.AS, OldSquad.DKK, OldSquad.inTeam, OldSquad.WD])},
    [OldSquad.BAT]: {with: new Set([OldSquad.st31, OldSquad.AXE, OldSquad.OT, OldSquad.RAF, OldSquad.TAG]), without: new Set([OldSquad.Apex, OldSquad.CU, OldSquad.KSK, OldSquad.RT])},
    [OldSquad.AXE]: {with: new Set([OldSquad.AV, OldSquad.RAF, OldSquad.RT, OldSquad.TAG, OldSquad.VOG]), without: new Set([OldSquad.BCS, OldSquad.inTeam, OldSquad.ODN, OldSquad.OT, OldSquad.RL])},
    [OldSquad.ORK]: {with: new Set([OldSquad.OT, OldSquad.TAG, OldSquad.W8]), without: new Set([OldSquad.st31, OldSquad.GROM, OldSquad.ISKRA, OldSquad.KSK, OldSquad.RON])},
    [OldSquad.st31]: {with: new Set([OldSquad.AV, OldSquad.AXE, OldSquad.FB, OldSquad.GROM, OldSquad.OT]), without: new Set([OldSquad.Apex, OldSquad.BAT, OldSquad.inTeam, OldSquad.RL, OldSquad.SGYR])},
    [OldSquad.GROM]: {with: new Set([OldSquad.st31, OldSquad.FB, OldSquad.GROM, OldSquad.RON]), without: new Set([OldSquad.Apex, OldSquad.AS, OldSquad.CU, OldSquad.OT, OldSquad.RAF, OldSquad.WD])},
    [OldSquad.KSK]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.FB, OldSquad.RAF, OldSquad.WD]), without: new Set([OldSquad.BAT, OldSquad.BCS, OldSquad.RL, OldSquad.SGYR, OldSquad.TAG])},
    [OldSquad.IT]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.FNX, OldSquad.GROM, OldSquad.TAG]), without: new Set([OldSquad.CU, OldSquad.DKK, OldSquad.ISKRA, OldSquad.ORK, OldSquad.RL, OldSquad.Wagner])},
    [OldSquad.SGYR]: {with: new Set([OldSquad.st31, OldSquad.AXE, OldSquad.inTeam, OldSquad.MSF, OldSquad.RAF]), without: new Set([OldSquad.CU, OldSquad.OT, OldSquad.RON, OldSquad.W8])},
    [OldSquad.RT]: {with: new Set([OldSquad.AS, OldSquad.RL, OldSquad.RON, OldSquad.TAG, OldSquad.VOG]), without: new Set([OldSquad.BAKR, OldSquad.BAT, OldSquad.Wagner])},
    [OldSquad.VOG]: {with: new Set([OldSquad.AS, OldSquad.ISKRA, OldSquad.RON, OldSquad.RT, OldSquad.W8]), without: new Set([OldSquad.st31, OldSquad.GROM, OldSquad.ODN, OldSquad.RAF, OldSquad.Wagner])},
    [OldSquad.MSF]: {with: new Set([OldSquad.st31, OldSquad.Apex, OldSquad.AV, OldSquad.AXE, OldSquad.RAF]), without: new Set([OldSquad.GROM, OldSquad.inTeam, OldSquad.ODN, OldSquad.W8, OldSquad.Wagner])},
    [OldSquad.CBR]: {with: new Set([OldSquad.st31, OldSquad.AV, OldSquad.CBR, OldSquad.CU, OldSquad.RAF]), without: new Set([OldSquad.AXE, OldSquad.FNX, OldSquad.IT, OldSquad.W8])},
    [OldSquad.CU]: {with: new Set([OldSquad.st31, OldSquad.AS, OldSquad.AV, OldSquad.AXE, OldSquad.OT]), without: new Set([OldSquad.BAKR, OldSquad.BAT, OldSquad.BCS, OldSquad.IT, OldSquad.RL])},
    [OldSquad.FNX]: {with: new Set([OldSquad.Apex, OldSquad.AV, OldSquad.TAG, OldSquad.W8]), without: new Set([OldSquad.st31, OldSquad.BAT, OldSquad.OT, OldSquad.RL, OldSquad.RON])},
    [OldSquad.AV]: {with: new Set([OldSquad.st31, OldSquad.AXE, OldSquad.CU, OldSquad.OT, OldSquad.RAF]), without: new Set([OldSquad.BAT, OldSquad.CBR, OldSquad.inTeam, OldSquad.SGYR, OldSquad.W8])},
    [OldSquad.W8]: {with: new Set([OldSquad.AV, OldSquad.AXE, OldSquad.FNX, OldSquad.KSK, OldSquad.OT]), without: new Set([OldSquad.inTeam, OldSquad.IT, OldSquad.RAF, OldSquad.RL, OldSquad.SGYR])},
};